### ISSUE TITLE
listing resident keys fails

### ISSUE THREAD

**Issue by leapfog** [token2/fido2-manage#12] opened 2024-09-30 19:15 UTC
I'm testing with an Authenton#1 key, trying to manage resident keys/passkeys.

`$ bash ./fido2-manage.sh -residentKeys -device 1 -domain passkey.org`

shows that there is a passkey for passkey.org, but the command

`$ bash ./fido2-manage.sh -residentKeys -device 1`

fails listing any relying parties with:

`fido2-token2: fido_credman_get_dev_rp: FIDO_ERR_MISSING_PARAMETER`

**Comment by leapfog** [comment] 2024-10-01 14:37
```
$ bash ./fido2-manage.sh -list
Device [1] : authenton authenton#1- CTAP2.1
```
```
$ bash ./fido2-manage.sh -info -device 1
[Info] Device 1 Information:
proto: 0x02
major: 0x00
minor: 0x00
build: 0x01
caps: 0x05 (wink, cbor, msg)
version strings: U2F_V2, FIDO_2_0, FIDO_2_1
extension strings: credBlob, credProtect, hmac-secret, largeBlobKey, minPinLength
aaguid: b267239b954f4041a01bee4f33c145b6
options: noep, rk, up, noalwaysUv, credMgmt, authnrCfg, clientPin, largeBlobs, setMinPINLength
fwversion: 0x0
maxmsgsiz: 1200
maxcredcntlst: 0
maxcredlen: 0
maxcredblob: 32
maxlargeblob: 1024
maxrpids in minpinlen: 8
minpinlen: 4
pin protocols: 1, 2
pin retries: 8
pin change required: false
uv retries: undefined
```

**Comment by leapfog** [comment] 2024-10-09 07:08
I successfully use libfido2 to list/manage resident keys on my Yubikey, but I cannot list them on the Authenton key:
```
$ fido2-token -L -r /dev/hidraw1
Enter PIN for /dev/hidraw1: 
fido2-token: fido_credman_get_dev_rp: FIDO_ERR_INVALID_CBOR
```
So I asked the Authenton support and they replied, they do not yet offer (Linux) software to manage their keys and pointed to your repo as a workaround. As your software can't list resident keys either, it seems the issue might be with their firmware.

In that case this issue could be closed/removed.

**Comment by token2** [comment] 2024-10-09 07:15
That is very strange, as it lists as FIDO_2_1, which means passkeys are supported. Are they FIDO-certified?

**Comment by leapfog** [comment] 2024-10-09 19:29
https://authenton.com/authentons-fido-certifications-.html

**Comment by token2** [comment] 2024-10-10 07:36
> https://authenton.com/authentons-fido-certifications-.html

Thanks, just to make sure the issue is not with libfido2, are you able to manage passkeys using Chromium tools? 
https://www.token2.com/site/page/managing-t2f2-fido2-keys-under-macos-or-linux

**Comment by leapfog** [comment] 2024-10-10 07:53
Chromium tools are also unable to manage the Authenton's passkeys.

So Authenton seems to support _creating_ and _using_ passkeys, but does not support _listing_ existing passkeys.

**Comment by token2** [comment] 2024-10-10 07:55
> Chromium tools are also unable to manage the Authenton's passkeys.
> 
> So Authenton seems to support _creating_ and _using_ passkeys, but does not support _listing_ existing passkeys.

So this means that their firmware is actually **FIDO2.0** , but they somehow got certified as 2.1.FINAL 

![image](https://github.com/user-attachments/assets/13476797-4ddc-4a5f-b77c-e2b89326fca4)

**Comment by leapfog** [comment] 2024-10-10 08:07
Asking the stick for details, **FIDO_2_1** is mentioned. -> I just asked (them) for a firmware upgrade.

**Comment by token2** [comment] 2024-11-26 10:09
Closing as the issue seems to be with firmware and not software. Feel free to reopen if needed

**Closed by token2** 2024-11-26 10:09 UTC
